name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'  # Runs daily at 4:15 AM UTC (9:45 AM IST)
  workflow_dispatch:      # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0           # Fetch all history for all branches and tags
          ref: ${{ github.ref }}   # Checkout the branch that triggered the workflow

      - name: Create or Append to Daily Log
        run: |
          # Ensure the file exists and append the log entry
          touch daily-log.txt
          echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          # Commit only if there are changes, avoid empty commits
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto commit at $(date -u)"
            git push
          fi
