name: Daily Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get current branch
        id: get_branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Create or Append to Daily Log
        run: |
          touch daily-log.txt
          echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto commit at $(date -u)"
            git push origin HEAD:${{ steps.get_branch.outputs.branch }}
          fi
